apiVersion: embeddedcluster.replicated.com/v1beta1
kind: Config
metadata:
  name: embedded-cluster-config
spec:
  version: 2.11.3+k8s-1.33
  domains:
    proxyRegistryDomain: "images.shortrib.io"
    replicatedAppDomain: "updates.shortrib.io"
