apiVersion: embeddedcluster.replicated.com/v1beta1
kind: Config
metadata:
  name: embedded-cluster-config
spec:
  version: "2.8.1+k8s-1.31"
  domains:
    proxyRegistryDomain: "images.shortrib.io"
    replicatedAppDomain: "updates.shortrib.io"
