apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: slackernews
spec:
  title: SlackerNews
  icon: "https://uploads-ssl.webflow.com/6310ad0e6a18aa1620da6ae8/6330e04f42bc6a7ba03b4725_snicon.png"
  ports:
    - serviceName: slackernews-nginx
      servicePort: 443
      localPort: 443
      applicationUrl: "https://slackernews"
