apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: slackernews
spec:
  # chart identifies a matching chart from a .tgz
  chart:
    name: slackernews
    chartVersion: $VERSION

  # values are used in the customer environment, as a pre-render step
  # these values will be supplied to helm template
  values:
    postgres:
      password: repl{{ ConfigOption "postgres_password"}}
    slack:
      botToken: repl{{ ConfigOption "slack_bot_token" }}
      userToken: repl{{ ConfigOption "slack_user_token" }}
      clientId: repl{{ ConfigOption "slack_clientid" }}
      clientSecret: repl{{ ConfigOption "slack_clientsecret" }}
    slackernews:
      domain: repl{{ ConfigOption "slackernews_domain" }}
    admin-console:
      enabled: false
    replicated:
      enabled: false
      preflights: false
      isKOTSManaged: true
    service:
      tls:
        enabled: true
        cert: |
          repl{{ ConfigOption "tls_cert" | nindent 10 }}
        key: |
          repl{{ ConfigOption "tls_key" | nindent 10 }}
    images:
      pullSecrets:
        replicated:
          dockerconfigjson: ""
      slackernews_api:
        pullSecret: repl{{ ImagePullSecretName }}
        repository: '{{repl HasLocalRegistry | ternary LocalRegistryHost "images.slackernews.io" }}/{{repl HasLocalRegistry | ternary LocalRegistryNamespace "proxy/slackernews/ghcr.io/slackernews" }}/slackernews-api'
      slackernews_migrations:
        pullSecret: repl{{ ImagePullSecretName }}
        repository: '{{repl HasLocalRegistry | ternary LocalRegistryHost "images.slackernews.io" }}/{{repl HasLocalRegistry | ternary LocalRegistryNamespace "proxy/slackernews/ghcr.io/slackernews" }}/slackernews-migrations'
      slackernews:
        pullSecret: repl{{ ImagePullSecretName }}
        repository: '{{repl HasLocalRegistry | ternary LocalRegistryHost "images.slackernews.io" }}/{{repl HasLocalRegistry | ternary LocalRegistryNamespace "proxy/slackernews/ghcr.io/slackernews" }}/slackernews-web'
  # builder values provide a way to render the chart with all images
  # and manifests. this is used in replicated to create airgap packages
  builder:
    postgres:
      password: repl{{ ConfigOption "postgres_password"}}
    admin-console:
      enabled: false
