version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/slackernews"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "build"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/deploy"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "build"
      include: "scope"
  - package-ecosystem: "helm"
    directories: 
      - "/chart/**/*"
    schedule:
      interval: "daily"
  - packges-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
