import { getSequelize } from "./db";
import { DataTypes } from 'sequelize';
import { randomUUID } from 'crypto';

export async function getApiTokenModel() {
  const model = (await getSequelize()).define('api_token', {
    id: {
      type: DataTypes.STRING,
      allowNull: false,
      primaryKey: true,
    },
    user_id: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    name: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    access_token: {
      type: DataTypes.STRING,
      allowNull: true,
    },
    created_at: {
      type: DataTypes.DATE,
      allowNull: false,
    },
    last_used_at: {
      type: DataTypes.DATE,
      allowNull: true,
    },
  }, {
    tableName: 'api_token',
    timestamps: false,
  });

  return model;
}

export interface ApiToken {
  id: string;
  userId: string;
  name: string;
  accessToken: string | null;
  createdAt: number;
  lastUsedAt: number | null;
}

export async function listApiTokens(userId: string): Promise<ApiToken[]> {
  if (!userId) {
    throw new Error('userId is required');
  }

  const tokens = await (await getApiTokenModel()).findAll({
    where: { user_id: userId },
    order: [['created_at', 'DESC']],
  });

  return tokens.map((t: any) => ({
    id: t.id,
    userId: t.user_id,
    name: t.name,
    accessToken: t.access_token || null,
    createdAt: t.created_at.getTime(),
    lastUsedAt: t.last_used_at ? t.last_used_at.getTime() : null,
  }));
}

export async function createApiToken(userId: string, name: string, accessToken?: string): Promise<{ token: ApiToken; jwt: string }> {
  const id = randomUUID();
  const createdAt = new Date();

  const token = await (await getApiTokenModel()).create({
    id,
    user_id: userId,
    name,
    access_token: accessToken || null,
    created_at: createdAt,
    last_used_at: null,
  });

  return {
    token: {
      id: token.id,
      userId: token.user_id,
      name: token.name,
      accessToken: token.access_token || null,
      createdAt: token.created_at.getTime(),
      lastUsedAt: null,
    },
    jwt: '', // JWT is generated by the caller using session.ts getApiTokenJwt
  };
}

export async function deleteApiToken(tokenId: string, userId: string): Promise<boolean> {
  if (!tokenId || !userId) {
    return false;
  }

  const result = await (await getApiTokenModel()).destroy({
    where: {
      id: tokenId,
      user_id: userId,
    },
  });

  return result > 0;
}

export async function getApiToken(tokenId: string): Promise<ApiToken | null> {
  if (!tokenId) {
    return null;
  }

  const token = await (await getApiTokenModel()).findOne({
    where: { id: tokenId },
  });

  if (!token) return null;

  return {
    id: token.id,
    userId: token.user_id,
    name: token.name,
    accessToken: token.access_token || null,
    createdAt: token.created_at.getTime(),
    lastUsedAt: token.last_used_at ? token.last_used_at.getTime() : null,
  };
}

export async function updateApiTokenLastUsed(tokenId: string): Promise<void> {
  if (!tokenId) {
    return;
  }

  await (await getApiTokenModel()).update({
    last_used_at: new Date(),
  }, {
    where: { id: tokenId },
  });
}
