{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
  name: slackernews-ingress
  annotations:
{{ .Values.ingress.annotations | toYaml | indent 6 }}
spec:
  rules:
  - host:  {{ .Values.slackernews.domain | quote}}
    http:
        paths:
        - backend:
            service:
              name: slackernews-api
              port:
                number: 3000
          path: /v1
          pathType: Prefix
        - backend:
            service:
              name: slackernews
              port:
                number: 3000
          path: /
          pathType: Prefix
{{ if .Values.service.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.slackernews.domain | quote}}
    secretName: {{  .Values.service.existingSecretName | default "slackernews-nginx" }}
{{ end }}
{{ end }}
