apiVersion: apps/v1
kind: Deployment
metadata:
  name: slackernews-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slackernews-nginx
  template:
    metadata:
      labels:
        app: slackernews-nginx
    spec:
      {{- include "slackernews.imagePullSecrets" . | nindent 6 }}
      containers:
      - image: {{ .Values.images.nginx.registry }}/{{ .Values.images.nginx.repository }}:{{ .Values.images.nginx.tag }}
        name: slackernews-nginx
        ports:
{{ if .Values.service.tls.enabled }}
        - containerPort: 443
          name: https
{{ else }}
        - containerPort: 8080
          name: http
{{ end }}
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/default.conf
          name: config
          subPath: default.conf
        - name: var-volume
          mountPath: /var/log/nginx
          readOnly: false
        - name: var-volume
          mountPath: /var/cache/nginx
          readOnly: false
        - name: var-volume
          mountPath: /var/run
          readOnly: false
{{ if .Values.service.tls.existingSecretName }}
        - mountPath: /certs/tls.crt
          name: certs
          subPath: {{ .Values.service.tls.existingSecretCertKey }}
        - mountPath: /certs/tls.key
          name: certs
          subPath: {{ .Values.service.tls.existingSecretKeyKey }}
{{ end }}
{{ if .Values.service.tls.enabled }}
        - mountPath: /certs/tls.crt
          name: certs
          subPath: tls.crt
        - mountPath: /certs/tls.key
          name: certs
          subPath: tls.key
{{ end }}
      volumes:
      - name: var-volume
        emptyDir: {}
      - configMap:
          name: slackernews-nginx
        name: config
{{ if .Values.service.tls.existingSecretName }}
      - secret:
          secretName: {{ .Values.service.tls.existingSecretName }}
        name: certs
{{ end }}
{{ if .Values.service.tls.enabled }}
      - secret:
          secretName: slackernews-nginx
        name: certs
{{ end }}
