name: deploy-replicated
on:
  push:
    branches:
      - deploy-cmx

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # - id: create-cluster
      #   uses: replicatedhq/compatibility-actions/create-cluster@v1
      #   with:
      #     api-token: ${{ secrets.REPLICATED_TOKEN }}
      #     kubernetes-distribution: k3s
      #     kubernetes-version: "1.28"
      #     ttl: 48h
      #     cluster-name: slackernews-${{ github.run_id }}

      - id: get-current-cluster-id
        uses: marccampbell/cloudflare-dns-action/get-dns-record@v1
        with:
          type: "TXT"
          name: "news-cluster-id.replicated.com"
          token: ${{ secrets.CLOUDFLARE_TOKEN }}
          zoneId: ${{ secrets.CLOUDFLARE_ZONE_ID }}

      - name: set-current-cluster-name
        uses: marccampbell/cloudflare-dns-action/get-dns-record@v1
        with:
          type: "TXT"
          name: "news-cluster-name.replicated.com"
          proxied: false
          # content: "${{ steps.create-cluster.outputs.cluster-id }}"
          content: "slackernews-${{ github.run_id }}"
          token: ${{ secrets.CLOUDFLARE_TOKEN }}
          zone: ${{ secrets.CLOUDFLARE_ZONE_ID }}

      # - name: delete-old-cluster
      #   uses: replicatedhq/compatibility-actions/remove-cluster@v1
      #   with:
      #     api-token: ${{ secrets.REPLICATED_TOKEN }}

      # - id: delete-cluster
      #   uses: replicatedhq/compatibility-actions/remove-cluster@v1
      #   with:
      #     cluster-id: ${{ steps.create-cluster.outputs.cluster-id }}
      #     api-token: ${{ secrets.REPLICATED_TOKEN }}
